// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCzfiDPTDoPzAfAN6u2_65dMl1a6ymqtA',
    appId: '1:654838352893:web:933137debb495c91216794',
    messagingSenderId: '654838352893',
    projectId: 'withnode-8d4c1',
    authDomain: 'withnode-8d4c1.firebaseapp.com',
    storageBucket: 'withnode-8d4c1.appspot.com',
    measurementId: 'G-ZVP5L4DC1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqWRBk7zh0KkwMfboXClx-ArbHQZLoWzo',
    appId: '1:654838352893:android:f39d5fc251dee3f3216794',
    messagingSenderId: '654838352893',
    projectId: 'withnode-8d4c1',
    storageBucket: 'withnode-8d4c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtFSbL1SrGR_1PnuzlsdTgFv70LyIqlSU',
    appId: '1:654838352893:ios:1d947a29aa1ef23b216794',
    messagingSenderId: '654838352893',
    projectId: 'withnode-8d4c1',
    storageBucket: 'withnode-8d4c1.appspot.com',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtFSbL1SrGR_1PnuzlsdTgFv70LyIqlSU',
    appId: '1:654838352893:ios:1d947a29aa1ef23b216794',
    messagingSenderId: '654838352893',
    projectId: 'withnode-8d4c1',
    storageBucket: 'withnode-8d4c1.appspot.com',
    iosBundleId: 'com.example.food',
  );
}
